name: PonWrt-HG5582A-PON
on:
  push:
    branches: [ main ]
  workflow_dispatch: # 网页手动一键触发编译
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 检出仓库文件
        uses: actions/checkout@v4

      - name: 扩容磁盘空间（必做，源码占用巨大）
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

  #  Install the required toolchain and libraries for building
  - name: 安装编译依赖
        run: |
sudo apt update -y
sudo apt full-upgrade -y
sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
  bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
  g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
  libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
  libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
  ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
  python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
  upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

#  Or use the ImmortalWrt one-click script to install dependencies
sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'

- name: 拉取 PonWrt 源码
        run: 
#  Clone the source code|
git clone https://github.com/pbs05/ponwrt.git
cd ponwrt


#  Update and install feeds (package sources)
./scripts/feeds update -a
./scripts/feeds install -a


#  Select a configuration, using 7581 as an example
- name: 导入HG5582A配置
        run: |
cp configs/an7581.config .config


- name: 预下载源码包
        run: |
#  Start building
# -j$(nproc) means compiling in parallel with all CPU cores to speed things up
make defconfig
make -j$(nproc)

- name: 上传固件成品
        uses: actions/upload-artifact@v4
        with:
          name: PonWrt-HG5582A-PON-Firmware
          path: openwrt/bin/targets/**/*.bin
          retention-days: 7
      
